### ISSUE TITLE
Copy all latest dev versions of gmap, location and staticmap to d7 subfolder of current repo

### ISSUE THREAD

**Issue by podarok** [drupal-ukraine/dmaps#1]
Please assign a human to do this

**Comment by ddrozdik** [comment]
I  can do this. What if I will add them as submodules? @podarok ^^

**Comment by podarok** [comment]
@DmitryDrozdik if you think it can be more convenient as submodules - do that

**Comment by ddrozdik** [comment]
This issue is done. I have added submodules to this repository. @podarok please close issue.
