### ISSUE TITLE
Investigate a list of features for all modules from d7 folder

### ISSUE THREAD

**Issue by podarok** [drupal-ukraine/dmaps#2]
blocker is #1

**Comment by podarok** [comment]
@DmitryDrozdik you can start to work on this

**Comment by podarok** [comment]
@DmitryDrozdik if you need any help with accesses to respective modules - feel free to ping me or @Sanchiz about that.

**Comment by ddrozdik** [comment]
Work is in progress. I will post a link to the doc here, when it will be at least partially ready.

**Comment by ddrozdik** [comment]
Doc with short description of features: https://docs.google.com/document/d/1jeexkSWFn7K_5VvN32eDirjkL1CcPogGPPXPWv5U8nU/edit
