### ISSUE TITLE
Code features that are going to be services for dmaps

### ISSUE THREAD

**Issue by podarok** [drupal-ukraine/dmaps#3]
from #2 describe a list of features that would be approached as Drupal services
Create a list of issues for respective services to be done

**Comment by ddrozdik** [comment]
Suggestions:
1 Location:
- earth.inc - Trigonometry for calculating geographical distances.
- service for getting supported locations, now they are located in the folder _/supported_ as separate files for each location.
- geoRSS -  location.georss.inc ??
- Location geocoder - this is almost all functions from location.inc
- possibly some other  that can be allocated from the Location module.

2 Gmap:
- Gmap strings
- Gmap marker
- GmapPolylineToolbox
- possibly some other that can be allocated from the Gmap module.

3 StaticMap
- Request to google API

@podarok your thoughts?

**Comment by podarok** [comment]
@DmitryDrozdik StaticMap ?

**Comment by podarok** [comment]
looks good. Let's roll this to ROADMAP.md file and pass the task to someone Newbie for getting commits @DmitryDrozdik
