### ISSUE TITLE
Location: Convert hook_flush_caches()

### ISSUE THREAD

**Issue by ddrozdik** [drupal-ukraine/dmaps#62]
Let's convert hook_flush_caches() into Drupal 8 format.
How to https://www.drupal.org/node/1561490

Table for cache is defined in the `dmaps.services.yml`

**Comment by Max-Kuzomko** [comment]
I found two cases of using hook_flush_caches.
1. The first case:

> /**
> - Implements hook_flush_caches().
>   */
>   function location_flush_caches() {
>   return array('cache_location');
>   }
1. Should we port the following code to dmaps module?

> /**
> - Implements hook_flush_caches().
>   *
> - @todo move this to GmapCacheToolbox
>   */
>   function gmap_flush_caches() {
>   gmap_regenerate_markers();
>   }

I can't see any *regenerate_markers function in dmaps module

**Comment by ddrozdik** [comment]
Maxim, as you can see in the title of the issue we are talking about Location module. You should port only that hook.

**Comment by Max-Kuzomko** [comment]
Thanks!
Please review PR:
https://github.com/drupal-ukraine/dmaps/pull/75
