### ISSUE TITLE
Location: Convert hook_token_list() && hook_token_values()

### ISSUE THREAD

**Issue by ddrozdik** [drupal-ukraine/dmaps#64]
**Blocker: hook schema with data structure**

In this task we should investigate how to convert hook_token_list() and hook_token_values() into drupal 8.

**Comment by afi13** [comment]
These hooks are useless in Drupal 7:
https://www.drupal.org/documentation/modules/token/update/6/7

> The hooks for providing tokens have been renamed. hook_token_list() is now hook_token_info(), and hook_token_values() is now hook_tokens(). Both hooks also have changed parameters and different return values than their D6 equivalents.

**Comment by afi13** [comment]
`location_token_info()` and `location_tokens()` will be ported in https://github.com/drupal-ukraine/dmaps/issues/24
